# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('usr_name', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
    ]
