# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='moment',
            name='usr_name',
            field=models.CharField(max_length=21),
        ),
    ]
